#!/bin/sh
#数据处理脚本：
#1.实现
#

echo "= Aflood 数据集展示工具 = —— 张公子"
echo
#验证参数个数
if [ ! "$#" = "4" ]; then
  cat 1>&2 <<_EOF_
用法:
$0 afl_state_dir graph_output_dir afl_states_dir 1/n_threads

afl_state_dir 		取自单线程AFL
graph_output_dir	图片输出文件夹
afl_states_dir		取自多线程Aflood，下面有多给个文件夹，命名格式 fuzzM / fuzzS1 2 ...
1/n_threads       线程数（1 : 单线程，n : aflood线程数）
_EOF_
  exit 1
fi
#环境验证
if [ "$AFL_ALLOW_TMP" = "" ]; then

  echo "$1" | grep -qE '^(/var)?/tmp/'
  T1="$?"

  echo "$2" | grep -qE '^(/var)?/tmp/'
  T2="$?"

  if [ "$T1" = "0" -o "$T2" = "0" ]; then

    echo "[-] Error: this script shouldn't be used with shared /tmp directories." 1>&2
    exit 1

  fi

fi
#检查是否有plot数据
if [ ! -f "$1/plot_data" ]; then

  echo "[-] Error: input directory is not valid (missing 'plot_data')." 1>&2
  exit 1

fi

BANNER="`cat "$1/fuzzer_stats" | grep '^afl_banner ' | cut -d: -f2- | cut -b2-`"

test "$BANNER" = "" && BANNER="(none)"

GNUPLOT=`which gnuplot 2>/dev/null`

if [ "$GNUPLOT" = "" ]; then

  echo "[-] Error: can't find 'gnuplot' in your \$PATH." 1>&2
  exit 1

fi

mkdir "$2" 2>/dev/null
if [ ! -d "$2" ]; then
  echo "[-] Error: unable to create the output directory - pick another location." 1>&2
  exit 1
fi

rm -f "$2/high_freq.png"
mv -f "$2/index.html" "$2/index.html.orig" 2>/dev/null

#开始生成图片

if [ "$4" = "1" ];then
  echo "[*] Generating plots..."
  (
  cat <<_EOF_
  set terminal png truecolor enhanced size 1000,300 butt

  set output '$2/high_freq.png'

  set xdata time
  set timefmt '%s'
  set format x "%b %d\n%H:%M"
  set tics font 'small'
  unset mxtics
  unset mytics

  set grid xtics linetype 0 linecolor rgb '#e0e0e0'
  set grid ytics linetype 0 linecolor rgb '#e0e0e0'
  set border linecolor rgb '#50c0f0'
  set tics textcolor rgb '#000000'
  set key outside

  set autoscale xfixmin
  set autoscale xfixmax

  plot '$1/plot_data' using 1:4 with filledcurve x1 title 'total paths' linecolor rgb '#000000' fillstyle transparent solid 0.2 noborder, \\
      '' using 1:3 with filledcurve x1 title 'current path' linecolor rgb '#f0f0f0' fillstyle transparent solid 0.5 noborder, \\
      '' using 1:5 with lines title 'pending paths' linecolor rgb '#0090ff' linewidth 3, \\
      '' using 1:6 with lines title 'pending favs' linecolor rgb '#c00080' linewidth 3, \\
      '' using 1:2 with lines title 'cycles done' linecolor rgb '#c000f0' linewidth 3

  set terminal png truecolor enhanced size 1000,200 butt
  set output '$2/low_freq.png'

  plot '$1/plot_data' using 1:8 with filledcurve x1 title '' linecolor rgb '#c00080' fillstyle transparent solid 0.2 noborder, \\
      '' using 1:8 with lines title ' uniq crashes' linecolor rgb '#c00080' linewidth 3, \\
      '' using 1:9 with lines title 'uniq hangs' linecolor rgb '#c000f0' linewidth 3, \\
      '' using 1:10 with lines title 'levels' linecolor rgb '#0090ff' linewidth 3

  set terminal png truecolor enhanced size 1000,200 butt
  set output '$2/exec_speed.png'

  plot '$1/plot_data' using 1:11 with filledcurve x1 title '' linecolor rgb '#0090ff' fillstyle transparent solid 0.2 noborder, \\
      '$1/plot_data' using 1:11 with lines title '    execs/sec' linecolor rgb '#0090ff' linewidth 3 smooth bezier;
_EOF_
  ) | gnuplot 
  if [ ! -s "$2/exec_speed.png" ]; then
    echo "[-] Error: something went wrong! Perhaps you have an ancient version of gnuplot?" 1>&2
    exit 1
  fi
  echo "[*] Generating index.html..."
  cat >"$2/index.html" <<_EOF_
  <table style="font-family: 'Trebuchet MS', 'Tahoma', 'Arial', 'Helvetica'">
  <tr><td style="width: 18ex"><b>Banner:</b></td><td>$BANNER</td></tr>
  <tr><td><b>Directory:</b></td><td>$1</td></tr>
  <tr><td><b>Generated on:</b></td><td>`date`</td></tr>
  </table>
  <p>
  <img src="high_freq.png" width=1000 height=300><p>
  <img src="low_freq.png" width=1000 height=200><p>
  <img src="exec_speed.png" width=1000 height=200>
_EOF_

  # Make it easy to remotely view results when outputting directly to a directory
  # served by Apache or other HTTP daemon. Since the plots aren't horribly
  # sensitive, this seems like a reasonable trade-off.

  chmod 755 "$2"
  chmod 644 "$2/high_freq.png" "$2/low_freq.png" "$2/exec_speed.png" "$2/index.html"

  echo "[+] All done - enjoy your charts!"

else
  
  echo "[*] 开始生成实验数据图"
  (

  cat <<_EOF_
  set terminal png truecolor enhanced size 1600,800 butt
  set output '$2/crash.png'

  # set grid xtics linetype 2 linecolor rgb '#e0e0e0'
  set grid ytics linetype 2 linecolor rgb '#e0e0e0'
  set border linecolor rgb '#000000'

  set xtics font 'times.ttf,20'
  set xtics offset 0,-0.75
  unset xtics

  set ytics font 'times.ttf,20'
  set ytics offset -1,0
  
  set key bottom right
  # set key box
  set key font 'times.ttf,20'

  set xlabel "0      1      2      3      4      5      6      7      8      9     10     11     12     13     14     15     16     17     18     19     20     21     22     23     24  Time(h)" font 'times.ttf,20' offset 7,-0.5
  set ylabel "Total Paths Count" font 'times.ttf,20' offset -2,0

  set autoscale xfixmin
  set autoscale xfixmax

  set title font 'times.ttf,80'
  plot  '$1/plot_data' using :8 with line title 'AFL unique crashes' linecolor rgb '#000000' linewidth 6, \\
        '$3/fuzzM/plot_data' using :8 with line title 'Aflood unique crashes thread 1' linecolor rgb '#000fff' linewidth 3, \\
        '$3/fuzzS1/plot_data' using :8 with line title 'Aflood unique crashes thread 2' linecolor rgb '#000fff' linewidth 3, \\
        '$3/fuzzS2/plot_data' using :8 with line title 'Aflood unique crashes thread 3' linecolor rgb '#000fff' linewidth 3

_EOF_

  ) | gnuplot 

  if [ ! -s "$2/crash.png" ]; then

    echo "[-] Error: something went wrong! Perhaps you have an ancient version of gnuplot?" 1>&2
    exit 1

  fi

  echo "[*] Generating index.html..."

  cat >"$2/index.html" <<_EOF_
  <p>
  <img src="crash.png" width=800><p>
_EOF_

  # Make it easy to remotely view results when outputting directly to a directory
  # served by Apache or other HTTP daemon. Since the plots aren't horribly
  # sensitive, this seems like a reasonable trade-off.

  chmod 755 "$2"
  chmod 644 "$2/crash.png" "$2/index.html"

  echo "[+] All done - enjoy your charts!"
fi

exit 0
